name: AquilaX Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  aquilax_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install AquilaX CLI
        run: |
          pip install aquilax

      - name: AquilaX Login and Set Defaults
        env:
          AQUILAX_API_TOKEN: ${{ secrets.AQUILAX_API_TOKEN }}
          AQUILAX_ORG_ID: ${{ secrets.AQUILAX_ORG_ID }}
          AQUILAX_GROUP_ID: ${{ secrets.AQUILAX_GROUP_ID }}
        run: |
          aquilax login "$AQUILAX_API_TOKEN"
          aquilax --set-org "$AQUILAX_ORG_ID"
          aquilax --set-group "$AQUILAX_GROUP_ID"

      - name: Run AquilaX Scan
        id: start_scan
        run: |
          echo "Starting AquilaX Security Scan..."
          aquilax scan "${{ github.repository_url }}" --sync > scan-output.json

          # Extract scan_id and project_id from the output
          SCAN_ID=$(jq -r '.scan_id' scan-output.json)
          PROJECT_ID=$(jq -r '.project_id' scan-output.json)
          echo "Scan started with SCAN_ID=$SCAN_ID and PROJECT_ID=$PROJECT_ID"
          echo "SCAN_ID=$SCAN_ID" >> $GITHUB_ENV
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Fetch Scan Details
        run: |
          echo "Fetching scan details..."
          aquilax get scan-details --project-id "$PROJECT_ID" --scan-id "$SCAN_ID" --format sarif > results.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

      - name: Check for Vulnerabilities
        run: |
          echo "Analyzing scan results..."
          vulnerabilities=$(jq '[.runs[].results[]] | length' results.sarif)
          echo "Vulnerabilities found: $vulnerabilities"
          if [ "$vulnerabilities" -gt 0 ]; then
            echo "::error::Scan completed with vulnerabilities!"
            exit 1
          else
            echo "No vulnerabilities found."
          fi
